### ISSUE TITLE
Installation issue: Error with xlm2 package

### ISSUE THREAD

**Issue by mbk-alt** [hessakh/MESgenCov#2]
After using `install_github("hessakh/MESgenCov")`I received the following error:

Using PKG_CFLAGS=-I/usr/include/libxml2
Using PKG_LIBS=-L/usr/lib -lxml2 -lz -lpthread -licucore -lm
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xml2’

Environment: Mac OS 10.15.3, R version 3.6.3, Rstudio 1.2.5033

**Comment by hessakh** [comment]
First run, in a terminal window:

xml2-config --cflags

Copy the output and put after “configure.vars=" in the following line of code:

install.packages("xml2",
                 configure.vars = c("INCLUDE_DIR=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2”))
